node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     def myTestContainer = docker.image('node:16')
     myTestContainer.pull()
     myTestContainer.inside {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('test with a DB') {
     def mysql = docker.image('mysql').run("-e MYSQL_ALLOW_EMPTY_PASSWORD=yes") 
     def myTestContainer = docker.image('node:16')
     myTestContainer.pull()
     myTestContainer.inside("--link ${mysql.id}:mysql") { // using linking, mysql will be available at host: mysql, port: 3306
          sh 'npm install --only=dev' 
          sh 'npm test'                     
     }                                   
     mysql.stop()
   }                                     
   stage('docker build/push') {            
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("ngocphupham/docker-demo-nodejs:${commit_id}", '.').push()
     }                                     
   }         
    stage('deploy'){
      docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
         def app = docker.image("ngocphupham/docker-demo-nodejs:${commit_id}").push()
         sh 'docker pull ngocphupham/docker-demo-nodejs:${commit_id}'
         sh 'docker stop my-app && docker rm my-app'
         sh 'docker run -d --name my-app -p 3000:3000 ngocphupham/docker-demo-nodejs:${commit_id}'
      }
   }                                   
}                                          
