version: "3.0"

services:
  app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT= 2003
    ports:
      - 2003:2003
    depends_on: 
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=root
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root/
    
