version: "3.0"

services:
  app:
    build: 
      context: .
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
    depends_on: 
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=root
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
